### ISSUE TITLE
[Mac] No Way to Move the Window Around

### ISSUE THREAD

**Issue by svenjr** [nathanchapman/graphiql-desktop#1]
I have noticed that there is no grab place on the window in order to move it around the screen. It is possible to resize to a place but once sized to what you want, you cannot then move it around. 

## Details
- OS: Mac OS Ventura Beta 13.1 (22C5033e)
- Machine: Apple 14" Macbook Pro M1 Pro
- GraphiQL Version: 0.0.1

**Comment by nathanchapman** [comment]
Resolved by #2
Will release in 0.1.0

**Comment by nathanchapman** [comment]
Sorry for the long delay here. I ran into some hiccups with the release, but it's out now!
https://github.com/nathanchapman/graphiql-desktop/releases/tag/v0.1.0
